import { SOLDIER_TYPES } from "./config.js";

/**
 * Mounted melee soldier type.
 * The shared soldier entity is mounted on a horse when spawned.
 */
SOLDIER_TYPES.cavalry = {
    id: "soldier:cavalry",
    displayName: "Kavallerie",
    mount: "minecraft:horse",
    levels: {
        1: { health: 36, attackRange: 1.8, speed: 0.38, damage: 6, knockbackResistance: 0.15, cost: 14, abilities: [], equipment: { mainhand: { item: "minecraft:iron_sword", amount: 1, enchantments: [{ id: "sharpness", level: 1 }] }, helmet: { item: "minecraft:iron_helmet", amount: 1, enchantments: [] }, chestplate: { item: "minecraft:leather_chestplate", amount: 1, enchantments: [] } } },
        2: { health: 46, attackRange: 1.9, speed: 0.41, damage: 8, knockbackResistance: 0.25, cost: 28, abilities: [{ id: "charge", name: "Sturmangriff", description: "Erhöht den Schaden beim ersten Angriff nach schneller Bewegung", cooldown: 20, duration: 5, effect: { type: "damage_boost", value: 1.35 } }], equipment: { mainhand: { item: "minecraft:iron_sword", amount: 1, enchantments: [{ id: "sharpness", level: 2 }, { id: "unbreaking", level: 1 }] }, helmet: { item: "minecraft:iron_helmet", amount: 1, enchantments: [{ id: "protection", level: 1 }] }, chestplate: { item: "minecraft:iron_chestplate", amount: 1, enchantments: [{ id: "protection", level: 1 }] } } },
        3: { health: 58, attackRange: 2.0, speed: 0.44, damage: 10, knockbackResistance: 0.35, cost: 48, abilities: [{ id: "charge", name: "Sturmangriff", description: "Starker Bonus beim Angriff aus der Bewegung", cooldown: 18, duration: 6, effect: { type: "damage_boost", value: 1.5 } }], equipment: { mainhand: { item: "minecraft:diamond_sword", amount: 1, enchantments: [{ id: "sharpness", level: 3 }, { id: "unbreaking", level: 2 }] }, helmet: { item: "minecraft:iron_helmet", amount: 1, enchantments: [{ id: "protection", level: 2 }] }, chestplate: { item: "minecraft:iron_chestplate", amount: 1, enchantments: [{ id: "protection", level: 2 }] } } },
        4: { health: 70, attackRange: 2.1, speed: 0.46, damage: 12, knockbackResistance: 0.45, cost: 68, abilities: [{ id: "charge", name: "Sturmangriff", description: "Sehr hoher Ansturmschaden", cooldown: 16, duration: 7, effect: { type: "damage_boost", value: 1.6 } }], equipment: { mainhand: { item: "minecraft:diamond_sword", amount: 1, enchantments: [{ id: "sharpness", level: 4 }, { id: "unbreaking", level: 3 }, { id: "mending", level: 1 }] }, helmet: { item: "minecraft:diamond_helmet", amount: 1, enchantments: [{ id: "protection", level: 3 }] }, chestplate: { item: "minecraft:diamond_chestplate", amount: 1, enchantments: [{ id: "protection", level: 3 }] } } },
        5: { health: 82, attackRange: 2.2, speed: 0.48, damage: 14, knockbackResistance: 0.55, cost: 92, abilities: [{ id: "charge", name: "Sturmangriff", description: "Massiver Ansturmschaden", cooldown: 15, duration: 8, effect: { type: "damage_boost", value: 1.7 } }], equipment: { mainhand: { item: "minecraft:netherite_sword", amount: 1, enchantments: [{ id: "sharpness", level: 4 }, { id: "unbreaking", level: 3 }, { id: "mending", level: 1 }] }, helmet: { item: "minecraft:diamond_helmet", amount: 1, enchantments: [{ id: "protection", level: 4 }, { id: "unbreaking", level: 2 }] }, chestplate: { item: "minecraft:diamond_chestplate", amount: 1, enchantments: [{ id: "protection", level: 4 }, { id: "unbreaking", level: 2 }] } } },
        6: { health: 94, attackRange: 2.3, speed: 0.50, damage: 16, knockbackResistance: 0.65, cost: 120, abilities: [{ id: "charge", name: "Sturmangriff", description: "Extremer Ansturmschaden", cooldown: 13, duration: 9, effect: { type: "damage_boost", value: 1.8 } }], equipment: { mainhand: { item: "minecraft:netherite_sword", amount: 1, enchantments: [{ id: "sharpness", level: 5 }, { id: "unbreaking", level: 3 }, { id: "mending", level: 1 }] }, helmet: { item: "minecraft:netherite_helmet", amount: 1, enchantments: [{ id: "protection", level: 4 }, { id: "unbreaking", level: 3 }] }, chestplate: { item: "minecraft:netherite_chestplate", amount: 1, enchantments: [{ id: "protection", level: 4 }, { id: "unbreaking", level: 3 }] } } },
        7: { health: 108, attackRange: 2.4, speed: 0.52, damage: 19, knockbackResistance: 0.75, cost: 155, abilities: [{ id: "charge", name: "Marschallsangriff", description: "Maximaler Ansturmschaden", cooldown: 12, duration: 10, effect: { type: "damage_boost", value: 2 } }], equipment: { mainhand: { item: "minecraft:netherite_sword", amount: 1, enchantments: [{ id: "sharpness", level: 5 }, { id: "unbreaking", level: 3 }, { id: "mending", level: 1 }, { id: "fire_aspect", level: 1 }] }, helmet: { item: "minecraft:netherite_helmet", amount: 1, enchantments: [{ id: "protection", level: 4 }, { id: "unbreaking", level: 3 }, { id: "mending", level: 1 }] }, chestplate: { item: "minecraft:netherite_chestplate", amount: 1, enchantments: [{ id: "protection", level: 4 }, { id: "unbreaking", level: 3 }, { id: "mending", level: 1 }] } } }
    }
};
