/**
 * Configuration for the monster-token TaxBonus system.
 *
 * TaxBonus is NOT generated by population. It is earned exclusively by
 * defeating monster tokens and is paid once with the next daily tax payout.
 */
export const TAX_BONUS_CONFIG = Object.freeze({
    /** Maximum bonus that can be stored for one team. */
    MAX_BONUS: 64,

    /** Maximum total tax payout for one team and day. */
    MAX_DAILY_PAYOUT: 256,

    /** Bonus awarded for defeating one token monster. */
    TOKEN_REWARD: 8
});

export function normalizeTaxBonus(value) {
    const number = Number(value);

    if (!Number.isFinite(number)) {
        return 0;
    }

    return Math.max(
        0,
        Math.min(TAX_BONUS_CONFIG.MAX_BONUS, Math.floor(number))
    );
}

export function addTokenTaxBonus(teamData, amount = TAX_BONUS_CONFIG.TOKEN_REWARD) {
    if (!teamData || typeof teamData !== "object") {
        return 0;
    }

    const current = normalizeTaxBonus(teamData.taxBonus);
    const reward = Math.max(0, Math.floor(Number(amount) || 0));
    const next = Math.min(
        TAX_BONUS_CONFIG.MAX_BONUS,
        current + reward
    );

    teamData.taxBonus = next;
    return next;
}

export function calculateTax(villagerCount, taxBonus) {
    const villagers = Math.max(0, Math.floor(Number(villagerCount) || 0));
    const bonus = normalizeTaxBonus(taxBonus);
    const total = Math.min(
        TAX_BONUS_CONFIG.MAX_DAILY_PAYOUT,
        villagers + bonus
    );

    return {
        villagers,
        bonus,
        total
    };
}
