import './spawn/SpawnSoldier.js';
import './spawn/SpawnSoldierFromGolem.js';
//UI
import './UI/soldierAction.js';
import './UI/ironGolemGuradAction.js';
//items
import './Items/PaperWritable.js';
import './Items/CopperShield.js';
import './Items/TeamCallHorn.js';
import './Items/TeamAttackHorn.js';
import './Items/TeamStandHorn.js';
import './Items/onMineBlock.js';
//functions
import './function/shootCannon.js';
import './function/shootBigCannon.js';
import './function/shootCatapult.js';
import './function/villagerFreeHandle.js';
import './function/tagArmorFunction.js';
import './function/playerTagNoDamage.js';
import './function/identificationOwner.js';
import './function/resetTarget.js';
import './function/teamSelecTable.js';
import './function/hayGolemCraft.js';
import './function/hitSuckBlood.js';
import './function/ironGolemGuardCraft.js';
import './function/suckBlood.js';
import './function/transformEntityTag.js';
import './function/shieldDamage.js';
import './function/villagerDinhCong.js';
import './function/soldierEvent.js';
import './function/tortoisPotatoCannon.js';
import './function/tortoisBallistaArrow.js';
import './function/ballistaShoot.js';
import './function/armyBookSystem.js';
//custom components
import './customComponents/luckyChest.js';
import './customComponents/freeHandleDecree.js';
import './customComponents/setArmorSpawn.js';
import './customComponents/flagTpItem.js';
//products villager
import './function/makingProduction.js';
import './function/masonProducts.js';
import './function/farmerProducts.js';
import './function/fisherProducts.js';
import './function/librarianProducts.js';
import './function/sheepOnShearSendEvent.js';
import './function/shepherdProducts.js';
import './function/clericProducts.js';
import './function/fletcherProducts.js';
import './function/cartographerProducts.js';
import './function/weaponsmithProducts.js';
import './function/toolsmithProducts.js';
import './function/butcherProducts.js';
import './function/leatherworkerProducts.js';